USE [master]
GO

/****** Object:  Database [db_biblioteca]    Script Date: 14/12/2018 11:45:24 ******/
CREATE DATABASE [db_biblioteca]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_biblioteca', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\db_biblioteca.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_biblioteca_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\db_biblioteca_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [db_biblioteca] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_biblioteca].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_biblioteca] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_biblioteca] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_biblioteca] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_biblioteca] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_biblioteca] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_biblioteca] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_biblioteca] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_biblioteca] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_biblioteca] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_biblioteca] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_biblioteca] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_biblioteca] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_biblioteca] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_biblioteca] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_biblioteca] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_biblioteca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_biblioteca] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_biblioteca] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_biblioteca] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_biblioteca] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_biblioteca] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_biblioteca] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_biblioteca] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_biblioteca] SET  MULTI_USER 
GO

ALTER DATABASE [db_biblioteca] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_biblioteca] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_biblioteca] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_biblioteca] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_biblioteca] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_biblioteca] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_biblioteca] SET  READ_WRITE 
GO

