//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_livro
    {
        public int li_cod { get; set; }
        public string li_nome { get; set; }
        public string li_colecao { get; set; }
        public Nullable<int> li_ano { get; set; }
        public string li_edicao { get; set; }
        public int us_cod { get; set; }
        public int ct_cod { get; set; }
        public int au_cod { get; set; }
        public int ed_cod { get; set; }
    
        public virtual tb_autor tb_autor { get; set; }
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_editora tb_editora { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario tb_usuario1 { get; set; }
    }
}
